/**
 * Loads and renders `supabase/migrations/*.sql`.
 *
 * There is exactly one source of truth for the schema — the migration files —
 * and this module only concatenates them in order. It exists so the SQL-Editor
 * workflow (`npm run db:sql`) applies byte-identical statements to the ones
 * `supabase db push` would apply, with no committed duplicate.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';

/** The migration set, in application order. */
export const EXPECTED_MIGRATIONS = Object.freeze([
  '0001_core_identity.sql',
  '0002_modules.sql',
  '0003_manager_agent.sql',
  '0004_rls_policies.sql',
  '0005_rls_hardening.sql',
  '0006_clients_crm.sql',
  '0007_content_storage.sql',
  '0008_social_connections.sql',
  '0009_publish_jobs.sql',
  '0010_unified_inbox.sql',
  '0011_email_templates_sending.sql',
  '0012_email_sequences_execution.sql',
  '0013_generated_media.sql',
]);

/**
 * Reads the migration set in order.
 *
 * @param {string} root repository root
 * @param {(sql: string) => string} [transform] per-file adjustment (used by the
 *   embedded-PostgreSQL harness, which has no pgcrypto extension)
 * @returns {{ name: string, sql: string }[]}
 */
export function loadMigrations(root, transform = (sql) => sql) {
  const dir = resolve(root, 'supabase/migrations');
  const names = readdirSync(dir)
    .filter((name) => name.endsWith('.sql'))
    .sort();

  const unexpected = names.filter((name) => !EXPECTED_MIGRATIONS.includes(name));
  const missing = EXPECTED_MIGRATIONS.filter((name) => !names.includes(name));
  if (unexpected.length > 0 || missing.length > 0) {
    throw new Error(
      `Migration set changed (missing: ${missing.join(', ') || 'none'}; unexpected: ${
        unexpected.join(', ') || 'none'
      }). Update EXPECTED_MIGRATIONS deliberately, after reviewing the new file.`,
    );
  }

  return EXPECTED_MIGRATIONS.map((name) => ({
    name,
    sql: transform(readFileSync(resolve(dir, name), 'utf8')),
  }));
}

/** Concatenates the migration set into one script, in order. */
export function renderMigrations(migrations) {
  const header = [
    '-- Nibrexo OS AI — complete migration set, generated from supabase/migrations/.',
    '--',
    '-- Generated by `npm run db:sql`. The migration files are the single source of',
    '-- truth; this file is only their concatenation in application order. Do not',
    '-- edit it — edit the migration and regenerate.',
    '--',
    '-- HOW TO USE: paste the whole file into the Supabase SQL Editor and run it once,',
    '-- or `psql "$DATABASE_URL" -f all_migrations.sql`. Then verify with',
    '-- `supabase/scripts/diagnose_schema.sql` (every row must read ok) and only then',
    '-- run `supabase/scripts/provision_owner.sql`.',
    '--',
    '-- Every statement is idempotent: `create table if not exists`, guarded',
    '-- `create type`, `drop policy if exists` + `create policy`. No statement',
    '-- deletes rows, and no statement drops a table, column or type.',
    '',
  ].join('\n');

  const body = migrations
    .map(
      (migration) =>
        `-- ${'='.repeat(74)}\n-- ${migration.name}\n-- ${'='.repeat(74)}\n\n${migration.sql.trim()}\n`,
    )
    .join('\n');

  return `${header}\n${body}`;
}
