/**
 * Image and video tools for the central Manager.
 *
 * Image bytes are saved only after a provider returns them. Video rendering
 * in Google Vids is assisted: the tool saves a draft package and does not
 * claim an MP4 exists.
 */

import { z } from 'zod';
import { mediaPreviewUrl } from '@/server/content/service';
import { resolveMediaStorage } from '@/server/content/storage';
import { ARENA_IMAGE_UNSUPPORTED, generateImage } from '@/server/integrations/media/image-generation';
import {
  buildVideoDraftPackage,
  renderVideoDraftBody,
  VIDS_ASSISTED_STEPS,
} from '@/server/integrations/media/video-draft';
import type { ContentStatus } from '@/types/domain';
import { readIdempotentOutput, storeIdempotentOutput } from '@/server/manager/idempotency';
import type { ToolContext } from '@/types/manager';
import { defineTool } from './define';

const libraryFields = {
  title: z.string().min(1).max(200),
  body: z.string().min(1).max(20000),
  caption: z.string().max(500).optional(),
  mediaUrl: z.string().max(1000).optional(),
};

async function saveDraft(
  ctx: ToolContext,
  input: { title: string; body: string; caption?: string; mediaUrl?: string },
) {
  return ctx.repo.contentItems.insert({
    organization_id: ctx.organizationId,
    title: input.title,
    caption: input.caption ?? null,
    body: input.body,
    status: 'DRAFT' as ContentStatus,
    platforms: [],
    media_url: input.mediaUrl ?? null,
    created_by: ctx.actor.userId,
  });
}

export const generateImageAssetTool = defineTool({
  name: 'generate_image_asset',
  description:
    'Generate an image with the native OpenAI Images API and save the PNG to the Content Library. Arena Agent Mode is unsupported and is not called. A missing key blocks the step; no placeholder image is saved.',
  permission: { module: 'content', action: 'create' },
  risk: 'low',
  inputSchema: z.object({
    title: z.string().min(1).max(200),
    prompt: z.string().min(1).max(4000),
    conceptTitle: z.string().max(200).optional(),
  }),
  async execute(input, ctx) {
    const cached = await readIdempotentOutput<Record<string, unknown>>(ctx);
    if (cached) return cached;

    const prompt = [input.prompt, input.conceptTitle ? `Visual concept: ${input.conceptTitle}` : null]
      .filter(Boolean)
      .join('\n')
      .slice(0, 3200);
    const generated = await generateImage({ prompt, signal: ctx.signal });

    if (generated.status === 'needs_configuration') {
      return {
        capabilityStatus: 'needs_configuration' as const,
        executed: false,
        imageAsset: null,
        arena: ARENA_IMAGE_UNSUPPORTED,
        missingConfig: generated.missing,
        message: generated.message,
      };
    }
    if (generated.status === 'error') {
      throw new Error(generated.message);
    }

    const storage = await resolveMediaStorage(ctx.repo.backend);
    if (!storage.ok) {
      return {
        capabilityStatus: 'needs_configuration' as const,
        executed: false,
        imageAsset: null,
        message: `${storage.error.message} The provider returned an image, but it was not saved. Retry after storage is configured; the idempotency key prevents a duplicate provider call only after a successful save.`,
      };
    }

    const filename = `${input.title.slice(0, 40).replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '') || 'image'}.png`;
    const storagePath = `${ctx.organizationId}/${ctx.idempotencyKey}-${filename}`;
    await storage.data.upload(storagePath, generated.bytes, generated.mimeType);
    const media = await ctx.repo.mediaFiles.insert({
      organization_id: ctx.organizationId,
      storage_path: storagePath,
      mime_type: generated.mimeType,
      size_bytes: generated.bytes.byteLength,
      created_by: ctx.actor.userId,
    });
    const mediaUrl = mediaPreviewUrl(media.id);
    const contentItem = await saveDraft(ctx, {
      title: input.title,
      caption: 'Generated image. Not published.',
      body: `Image generated by ${generated.provider} model ${generated.model}. Prompt used:\n${prompt}\n\nThis file is a draft in the Content Library. It has not been published.`,
      mediaUrl,
    });

    const output = {
      capabilityStatus: 'available' as const,
      executed: true,
      imageAsset: {
        provider: generated.provider,
        model: generated.model,
        mediaId: media.id,
        bytes: generated.bytes.byteLength,
      },
      media,
      contentItem,
      message: `Image saved to the Content Library as ${contentItem.title}. It has not been published.`,
    };
    await storeIdempotentOutput(ctx, output);
    return output;
  },
});

export const prepareVideoDraftTool = defineTool({
  name: 'prepare_video_draft',
  description:
    'Save a Google Vids draft package (scenes, narration, assisted steps) to the Content Library. Does not render or export a video file.',
  permission: { module: 'content', action: 'create' },
  risk: 'low',
  inputSchema: z.object({
    title: z.string().min(1).max(200),
    brief: z.string().min(1).max(8000),
  }),
  async execute(input, ctx) {
    const cached = await readIdempotentOutput<Record<string, unknown>>(ctx);
    if (cached) return cached;

    const videoDraft = buildVideoDraftPackage(input);
    const contentItem = await saveDraft(ctx, {
      title: `${input.title} — video draft`,
      caption: 'Google Vids draft package. No video file rendered.',
      body: renderVideoDraftBody(videoDraft),
    });
    const output = {
      capabilityStatus: 'assisted' as const,
      executed: true,
      videoDraft,
      contentItem,
      renderedVideo: null,
      message:
        'Video draft package saved to the Content Library. Google Vids has no public create/edit/export API, so no video file was rendered.',
    };
    await storeIdempotentOutput(ctx, output);
    return output;
  },
});

export const exportVideoFileTool = defineTool({
  name: 'export_video_file',
  description:
    'Would export a rendered video. Google Vids does not offer a public export API, so this step stays assisted and does not create a file.',
  permission: { module: 'content', action: 'create' },
  risk: 'low',
  inputSchema: z.object({
    title: z.string().min(1).max(200),
  }),
  async execute(input) {
    return {
      capabilityStatus: 'assisted' as const,
      executed: false,
      title: input.title,
      renderedVideo: null,
      assistedSteps: [...VIDS_ASSISTED_STEPS],
      message: `No video file was exported for "${input.title}". ${VIDS_ASSISTED_STEPS[0]} Remaining steps are assisted in Google Vids. Upload the MP4 to the Content Library when you have reviewed it.`,
    };
  },
});

export const saveLibraryAssetTool = defineTool({
  name: 'save_library_asset',
  description: 'Save a completed text asset to the Content Library as a draft. Does not publish it.',
  permission: { module: 'content', action: 'create' },
  risk: 'low',
  inputSchema: z.object(libraryFields),
  async execute(input, ctx) {
    const cached = await readIdempotentOutput<Record<string, unknown>>(ctx);
    if (cached) return cached;
    const contentItem = await saveDraft(ctx, input);
    const output = {
      capabilityStatus: 'available' as const,
      executed: true,
      contentItem,
      message: `Saved "${contentItem.title}" to the Content Library as a draft.`,
    };
    await storeIdempotentOutput(ctx, output);
    return output;
  },
});

export const mediaTools = [
  generateImageAssetTool,
  prepareVideoDraftTool,
  exportVideoFileTool,
  saveLibraryAssetTool,
];
