/**
 * Phase 18 regression: deliverable previews come from the stored bytes, are
 * bounded, and decode what the writers escaped. DOCX fixtures are generated by
 * the project's own writer, so they are real files; the text is test data.
 */
import { describe, expect, it } from 'vitest';
import { buildDocx } from '@/server/artifacts/docx';
import { toCsv } from '@/server/artifacts/csv';
import { docxParagraphs, decodeXmlText, parseCsv, previewArtifact, PREVIEW_MAX_ROWS } from '@/server/artifacts/preview';

const encode = (text: string) => new TextEncoder().encode(text);

describe('CSV preview parsing', () => {
  it('handles quoted commas, doubled quotes, embedded newlines and CRLF', () => {
    const rows = parseCsv('name,notes\r\n"Clinic, Lahore","said ""yes""\nthen left"\r\nB,plain\r\n');
    expect(rows).toEqual([
      ['name', 'notes'],
      ['Clinic, Lahore', 'said "yes"\nthen left'],
      ['B', 'plain'],
    ]);
  });

  it('round-trips the project CSV writer output exactly', () => {
    const csv = toCsv(['name', 'source'], [['Sindh Smile', 'Owner, interview "notes"']]);
    const preview = previewArtifact({ format: 'csv', bytes: encode(csv) });
    expect(preview).toEqual({
      kind: 'table',
      headers: ['name', 'source'],
      rows: [['Sindh Smile', 'Owner, interview "notes"']],
      totalRows: 1,
    });
  });

  it('caps the rows shown and reports the full count', () => {
    const rows = Array.from({ length: PREVIEW_MAX_ROWS + 10 }, (_, index) => [`lead ${index}`]);
    const preview = previewArtifact({ format: 'csv', bytes: encode(toCsv(['name'], rows)) });
    expect(preview.kind).toBe('table');
    if (preview.kind !== 'table') return;
    expect(preview.rows).toHaveLength(PREVIEW_MAX_ROWS);
    expect(preview.totalRows).toBe(PREVIEW_MAX_ROWS + 10);
  });
});

describe('DOCX preview text', () => {
  it('extracts the paragraphs the writer produced, with escaped characters decoded', () => {
    const bytes = buildDocx({
      title: 'Brief A & B',
      meta: [['Domain', 'Dental <software>']],
      generatedAt: '2026-10-10T00:00:00.000Z',
      sections: [
        { heading: 'Evidence', paragraphs: ['Clinics report fewer missed bookings (test fixture).'] },
      ],
    });
    const preview = previewArtifact({ format: 'docx', bytes });
    expect(preview.kind).toBe('text');
    if (preview.kind !== 'text') return;
    expect(preview.paragraphs).toContain('Brief A & B');
    expect(preview.paragraphs).toContain('Clinics report fewer missed bookings (test fixture).');
    expect(preview.paragraphs.join('\n')).toContain('Dental <software>');
  });

  it('decodes numeric and named XML entities', () => {
    expect(decodeXmlText('A &amp; B &lt;C&gt; &quot;q&quot; &#39;x&#39; &#x41;')).toBe('A & B <C> "q" \'x\' A');
  });

  it('drops empty paragraphs', () => {
    expect(docxParagraphs('<w:p></w:p><w:p><w:r><w:t>Kept</w:t></w:r></w:p>')).toEqual(['Kept']);
  });
});

describe('preview failure modes', () => {
  it('reports an unsupported format without reading the file', () => {
    const preview = previewArtifact({ format: 'pdf', bytes: encode('%PDF-1.4') });
    expect(preview.kind).toBe('unsupported');
  });

  it('returns a structured error for bytes that are not a valid document', () => {
    const preview = previewArtifact({ format: 'docx', bytes: encode('not a zip file at all, just text') });
    expect(preview.kind).toBe('error');
    if (preview.kind !== 'error') return;
    expect(preview.message).not.toMatch(/stack|at /i);
  });
});
